version: "3.9"

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80" # Map the container's port 80 to the host's port 80
    environment:
      - NODE_ENV=production
